# Generated by Django 3.2.2 on 2021-05-10 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='created_at',
            field=models.DateField(auto_now_add=True, default="2021-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
