# Generated by Django 3.2.2 on 2021-05-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'verbose_name_plural': 'Waitlist Entries'},
        ),
    ]
