# Generated by Django 3.2.2 on 2021-05-08 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waitlist', '0003_waitlistentry_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user'),
            preserve_default=False,
        ),
    ]
