# Generated by Django 3.2.2 on 2021-05-08 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectures', '0002_auto_20210508_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='is_required',
            new_name='required',
        ),
        migrations.AddField(
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')], default=1),
        ),
        migrations.AddField(
            model_name='lecture',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user'),
            preserve_default=False,
        ),
    ]
